# Generated by Django 5.1.1 on 2024-09-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_alter_task_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tags", to="todo.tag"
            ),
        ),
    ]
